version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    command: npm run dev
    stdin_open: true
    tty: true

    volumes:
      - ./client/src:/app/src

    environment:
      - WDS_SOCKET_PORT=0

  server:
    command: npm run dev

    volumes:
      - ./server/src:/app/src

    environment:
      - NODE_ENV=development
      - EMAIL_HOST=smtp.mailtrap.io
      - EMAIL_PORT=2525
      - EMAIL_USERNAME=f41745fbcb1f7a
      - EMAIL_PASSWORD=8e1b84744ec7e9

  nginx:
    volumes:
      - ./nginx/dev.conf.template:/etc/nginx/templates/default.conf.template
